### ISSUE TITLE
TODO CSS 

### ISSUE THREAD

**Issue by mathieu-roquet** [guimelcode/new_portique_theme#11]
- [x] Ajout de padding en haut de la grille
- [ ] Ajout de padding en bas des articles
- [x] Ajout du logo LP en SVG
- [ ] Stylisation de la simpleBar
- [ ] Soulignement des éléments sélectionnés dans le `#topmenu` -> blink
- [ ] Stylisation du module "Langue" (Mobile + Desktop)
- [ ] Uniformisation des tailles de corps de la typo du menu (responsive)
