### ISSUE TITLE
TODO JS

### ISSUE THREAD

**Issue by guimelcode** [guimelcode/new_portique_theme#12]
- [ ] Refaire module animation de chargement des articles "Archives" ; 
- [ ] Affecter le script de modification du module "Langues" à la version mobile (ou la rendre générale) ; 
- [ ] Nettoyer tout le code ; 
- [ ] Clarifier les instances Swiper.js et SimpleBar.js ; 
- [ ] Nettoyer la partie State ;
