### ISSUE TITLE
TODO PHP

### ISSUE THREAD

**Issue by guimelcode** [guimelcode/new_portique_theme#13]
- [x] Réorganisation de l'ordre des pages dans la Catégorie "Informations"
- [ ] Nettoyer les commentaires et parties inutiles **(en cours)**;
   - [x] Dossier Includes ;
- [ ] Faire page-template pour un formulaire pour la Newsletter
